### Basic Get Request Retriving an array of albums.
GET localhost:8080/albums
Accept: application/json


### Add a new album to collection
POST http://localhost:8080/albums
Content-Type: application/json

{
  "id": "4",
  "title": "The Modern Sound of Betty Carter",
  "artist": "Betty Carter",
  "price": 49.99
}

###

